### PR TITLE
Issue14 - get arduino_ulp working on esp32 v1.0.1

### PR DESCRIPTION
**Pull request by unixbigot**
This is not ready to merge yet, but I'd like your opinion on the re-organisation and also why the
ulp_main_bin_end/start symbols aren't generated.

### CODE REVIEW

**Comment by duff2013** [comment]
I'll get up to speed on this later tonight but looks promising, the symbols issue could be due to the [compiler.c.elf.flags](https://github.com/duff2013/arduino_ulp/blob/master/platform.txt#L47) needing edited to include the 'ulp_main.ld' file generated during compile in the platform.txt though I only glanced at what you did so far.

**Comment by duff2013** [comment]
Went over this a little bit and I guess you are dealing with the compiler flags to include the ulp_main.ld with your script? I haven't dug into the script yet but got that from your comments. 

So couple of things:

1. I don't think we should rename the README.rst to ULP.md, that is directly from Espressif and not something I created. Maybe just delete it from the download.

2. In esp32ulp_build_recipe.py -> Code "(out, err) = proc.communicate()" I believe the actual error from the compiler will be in the stdout not stderr that why I used the "out" variable.

3. I need to think about changing where "esp32ulp_build_recipe.py", and "esp32ulp-elf-binutils" file and folders live that you have proposed. My thinking was put them in the same logical place that esp-idf files are meaning "esp32ulp-elf-binutils" folder should live with "xtensa-esp32-elf-gcc" since they are both compilers and that how the esp-idf does it. Also the "esp32.ulp.ld" file in esp-idf lives in the component folder ulp that why put it there in my install though I see why you put it in the "ld" folder. 

Anyway I'll wait until you are ready to merge before commenting again.

**Comment by unixbigot** [comment]
> Went over this a little bit and I guess you are dealing with the compiler flags to include the ulp_main.ld with your script? I haven't dug into the script yet but got that from your comments.
> 
> So couple of things:
> 
> 1. I don't think we should rename the README.rst to ULP.md, that is directly from Espressif and not something I created. Maybe just delete it from the download.

Oh, ok, no point distributing a copy of someone else's file that could just go out of date.

> 2. In esp32ulp_build_recipe.py -> Code "(out, err) = proc.communicate()" I believe the actual error from the compiler will be in the stdout not stderr that why I used the "out" variable.

I found the opposite.  By not printing out the standard error output, errors were being silently discarded.

> 3. I need to think about changing where "esp32ulp_build_recipe.py", and "esp32ulp-elf-binutils" file and folders live that you have proposed. My thinking was put them in the same logical place that esp-idf files are meaning "esp32ulp-elf-binutils" folder should live with "xtensa-esp32-elf-gcc" since they are both compilers and that how the esp-idf does it. Also the "esp32.ulp.ld" file in esp-idf lives in the component folder ulp that why put it there in my install though I see why you put it in the "ld" folder.

I attempted to do that.  I see that it is convenient for installation to just drag a single folder into the board area, but include/ is meant to be for header files only.

I am stuck as to where `_binary_ulp_main_bin_start` can be found.   Nothing seems to generate this in the compilation process.   I wonder if the arduino core 1.0.1 removed it?

> Anyway I'll wait until you are ready to merge before commenting again.

I have another revision that also works for the arduino-cli tool.   But still I cannot get past being unable to resolve `bin_start` and `bin_end`

**Comment by unixbigot** [comment]
> Anyway I'll wait until you are ready to merge before commenting again.

I should mention that the reason I am doing this simplification is that the arduino_ulp master does not work for me with the 1.0.1 arduino-esp32 at all, and I am trying to understand why.  

I have a client for whom 1.0.1 fixes bugs, and I'm unable to get my code to build at all for the last week.

Can you pleae tell me what version of arduino-esp32 *does* work seamlessly with arduino_ulp?  It appears to be neither 1.0.0 nor 1.0.1.  One of the betas?

**Comment by duff2013** [comment]
> I am stuck as to where _binary_ulp_main_bin_start can be found. Nothing seems to generate this in the compilation process. I wonder if the arduino core 1.0.1 removed it?

Hope this not the case, it would be a shame if they did. _binary_ulp_main_bin_start would be part of the ULP binary but I'm not sure what precompiled part it would be located in? I can say the esp people on their forum didn't say much or seemed like they even cared about this for Arduino when I brought it up.

> Can you pleae tell me what version of arduino-esp32 does work seamlessly with arduino_ulp? It appears to be neither 1.0.0 nor 1.0.1. One of the betas?

I used the board manager to download and install the "Stable release link:" using the instructions [here](https://github.com/espressif/arduino-esp32/blob/master/docs/arduino-ide/boards_manager.md). I've successfully compiled using both Arduino 1.8.8, 1.8.7. 

I'll try to see if I can get v1.0.1 working today and let you know what I find.

**Comment by duff2013** [comment]
I can confirm the error your seeing using v1.0.1 and its very strange but I think it has something to do with this [thread](https://github.com/espressif/esp-idf/issues/2157). I afraid I will have to download the esp-idf and build a ulp program from there and see how those symbols are made but what version of the idf corresponds to the Arduino's v1.0.1?

**Comment by duff2013** [comment]
I'm going to do a pull later tonight or tomorrow that might break some of your pulls. My fixes to **esp32ulp_build_recipe.py** will make not having to edit the platform.txt anymore and just use the platform.local.txt, I hope. It also will work with both v1.0.0 and v1.0.1. 

I'm leaning toward having everything located in the ../esp32/tools/ because I noticed that it does not get deleted when installing a new core through he board manager (Mac OS tested only so far). The user will still have to copy the platform.local.txt back to where the platform.txt folder is (or your script would take care of that).

So one thing for the automated install script you posted, I wonder if the user doesn't have the binutils compiler downloaded and installed yet if the script could do that for them? Not sure how that would happen with standard OS install? Probably have to assume users would not have anything installed on the computer to do that like git or such.

**Comment by unixbigot** [comment]
The github api gives us the information about the release file via ```curl https://api.github.com/repos/espressif/binutils-esp32ulp/releases```

Given that we obviously assume the user has Python installed, a binutils downloader script is do-able.   

Come to think of it, python might work better than bash for a fully portable install script; better than trying to remember how to get `XCOPY.EXE` to behave.

**Comment by 2010019970909** [comment]
Hello,

I'm modifying the two scripts for python 3.7 ([ulp_scripts_py3.7.zip](https://github.com/duff2013/arduino_ulp/files/2777123/ulp_scripts_py3.7.zip)). It's not fully working on the version 1.0.0 (see issue #18) and it don't work on version 1.0.1 (``undefined reference to `vRingbufferReturnItem'``, etc), but I think the simplest way to find the version is to analyse the plateform path:

```
def gen_XTENSA_AR_cmd(build_path, compiler_path, file, board_options, ppath):
    core_version = ppath[ppath.rfind('\\')+1:] # Get the version
    print(core_version) # Test: Show the version number
    #cmds = gen_cmds(os.path.join(platform_path, 'tools'))
    cmds = gen_xtensa_cmds(compiler_path)
    file_names_constant = gen_file_names_constant()
    XTENSA_AR = []
    XTENSA_AR.append(cmds['XTENSA_AR'])
    XTENSA_AR.append(EXTRA_FLAGS['CRU'])
    ## Select the good working path
    if core_version=="1.0.0":
        XTENSA_AR.append(os.path.join(build_path, 'arduino.ar'))
    else:
        XTENSA_AR.append(os.path.join(build_path, 'core', 'core.a'))
    XTENSA_AR.append(file_names_constant['bin_o'])
    STR_CMD = ' '.join(XTENSA_AR)
    return STR_CMD, XTENSA_AR
```

Maybe it can work under python 2.7.

**Comment by duff2013** [comment]
@2010019970909 Thanks, I'll take a look at this tonight, pretty much been working on the same thing too.

**Comment by unixbigot** [comment]
I've been away at a conference in New Zealand but I'm back now.

I have updated this PR with a version of install.sh that will find and fetch the esp32-ulp-binutils.

I don't have access to a windows machine today to port the install script to python, but can try this tomorrow.

**Comment by 2010019970909** [comment]
Hello,

I've a tested base for a python [script].(https://github.com/2010019970909/arduino_ulp/blob/master/setup_ulp.py). I've tested it on W10, Linux (Mint 19.1 in VM) and on Python2 and 3. It works online (standalone) and offline (in the extracted folder of the repo). It should be compatible with Mac OS too (but not yet tested). You just have to set the url of the zip file of this repo (https://github.com/duff2013/arduino_ulp/archive/master.zip). Let me know if I have to make changes for the installation method (like for the platform file). Also this script doesn't install the examples (I will try to read the preference.txt file if found it and find the sketch directory to copy the sketches, but I think it can be better to put these examples in an empty library).

**Comment by duff2013** [comment]
just so you know I'm going to change this repositories name to **ulptool**, then I'll start looking at these pulls, don't know what that will do to this pull but I hope it just comes through but if not I apologize. I was waiting until things die down a bit so I'm thinking tomorrow or the next day I will pull the trigger and change the name.

**Comment by duff2013** [comment]
I uploaded a fix to for the different versions, I was appending the ulp code to the core archive but thats not the best way to do this, now I'm adding the object file directly to the gcc linker which should work with any version they put out. Also I changed how the install is done so we don't have to move so many files around anymore. This pull will be closed now.
